<?
$Countries = array("United States" => "United States of America", "Canada" => "Canada",
    "Afghanistan" => "Afghanistan","Albania" => "Albania", "Algeria" => "Algeria",
    "American Samoa" => "American Samoa","Andorra" => "Andorra","Angola" => "Angola",
    "Anguilla" => "Anguilla", "Antarctica" => "Antarctica","Antigua And Barbuda" => "Antigua And Barbuda",
    "Argentina" => "Argentina", "Armenia" => "Armenia","Aruba" => "Aruba","Australia" => "Australia",
    "Austria" => "Austria", "Azerbaijan" => "Azerbaijan","Bahamas" => "Bahamas","BHR" => "Bahrain",
    "Bahrain" => "Bangladesh", "Barbados" => "Barbados","Belarus" => "Belarus", "Belgium" => "Belgium",
    "Belize" => "Belize", "Benin" => "Benin", "Bermuda" => "Bermuda", "Bhutan" => "Bhutan", "Bolivia" => "Bolivia",
    "Bosnia And Herzegowina" => "Bosnia And Herzegowina","Botswana" => "Botswana","Bouvet Island" => "Bouvet Island",
    "Brazil" => "Brazil","Brunei Darussalam" => "Brunei Darussalam","Bulgaria" => "Bulgaria",
    "Burkina Faso" => "Burkina Faso", "Burundi" => "Burundi", "Cambodia" => "Cambodia","Cameroon" => "Cameroon",
    "Cape Verde" => "Cape Verde","Cayman Islands" => "Cayman Islands", "Central African" => "Central African Republic",
    "Chad" => "Chad","Chile" => "Chile", "China" => "China","Christmas Island" => "Christmas Island",
    "Cocos Islands" => "Cocos Islands", "Columbia" => "Columbia", "Comoros" => "Comoros",
    "Congo" => "Congo", "Cook Islands" => "Cook Islands", "Costa Rica" => "Costa Rica",
    "Cote D'Ivoire" => "Cote D'Ivoire", "Croatia" => "Croatia",  "Cuba" => "Cuba", "Cyprus" => "Cyprus",
    "Czech Republic" => "Czech Republic", "Denmark" => "Denmark", "Djibouti" => "Djibouti","Dominica" => "Dominica",
    "Dominican Republic" => "Dominican Republic","East Timor" => "East Timor","Ecuador" => "Ecuador",
    "Egypt" => "Egypt",  "El Salvador" => "El Salvador", "Equatorial Guinea" => "Equatorial Guinea",
    "Eritrea" => "Eritrea", "Estonia" => "Estonia", "Ethiopia" => "Ethiopia", "Falkland Islands" => "Falkland Islands",
    "Faroe Islands" => "Faroe Islands","Fiji" => "Fiji", "Finland" => "Finland", "France" => "France",
    "France Metropolitan" => "France Metropolitan", "French Guiana" => "French Guiana", "French Polynesia" => "French Polynesia",
    "Gabon" => "Gabon", "Gambia" => "Gambia", "Germany" => "Germany", "Ghana" => "Ghana", "Gibraltar" => "Gibraltar",
    "Greece" => "Greece", "Greenland" => "Greenland","Grenada" => "Grenada","Guadeloupe" => "Guadeloupe",
    "Guam" => "Guam", "Guatemala" => "Guatemala","Guinea" => "Guinea", "Guinea-Bissau" => "Guinea-Bissau",
    "Guyana" => "Guyana",  "Haiti" => "Haiti", "Honduras" => "Honduras","Hong Kong" => "Hong Kong",
    "Hungary" => "Hungary","Iceland" => "Iceland", "India" => "India", "Indonesia" => "Indonesia",
    "Iran" => "Iran", "Iraq" => "Iraq", "Ireland" => "Ireland",  "Israel" => "Israel", "Italy" => "Italy",
    "Jamaica" => "Jamaica", "Japan" => "Japan", "Jordan" => "Jordan", "Kazakhstan" => "Kazakhstan",
    "Kenya" => "Kenya", "Kiribati" => "Kiribati", "Korea, Republic of" => "Korea, Republic of",
    "Kuwait" => "Kuwait", "Kyrgyzstan" => "Kyrgyzstan", "Laos" => "Laos", "Latvia" => "Latvia",
    "Lebanon" => "Lebanon",  "Lesotho" => "Lesotho", "Liberia" => "Liberia", "Libya" => "Libya",
    "Liechtenstein" => "Liechtenstein", "Lithuania" => "Lithuania", "Luxembourg" => "Luxembourg",
    "Macao" => "Macao",  "Macedonia" => "Macedonia", "Madagascar" => "Madagascar",  "Malawi" => "Malawi",
    "Malaysia" => "Malaysia","Maldives" => "Maldives", "Mali" => "Mali", "Malta" => "Malta",
    "Marshall Islands" => "Marshall Islands","Martinique" => "Martinique","Mauritania" => "Mauritania",
    "Mauritius" => "Mauritius","Mayotte" => "Mayotte","Mexico" => "Mexico","Micronesia" => "Micronesia",
    "Moldova" => "Moldova","Monaco" => "Monaco","Mongolia" => "Mongolia","Montserrat" => "Montserrat",
    "Morocco" => "Morocco", "Mozambique" => "Mozambique", "Myanmar" => "Myanmar","Namibia" => "Namibia",
    "Nauru" => "Nauru", "Nepal" => "Nepal","NLD" => "Netherlands","Netherlands" => "Netherlands Antilles",
    "New Zealand" => "New Zealand", "New Caledonia" => "New Caledonia","Nicaragua" => "Nicaragua",
    "Niger" => "Niger", "Nigeria" => "Nigeria", "Niue" => "Niue","Norfolk island" => "Norfolk island",
    "Mariana Islands" => "Northern Mariana Islands", "Norway" => "Norway", "Oman" => "Oman",
    "Pakistan" => "Pakistan", "Palau" => "Palau",  "Palestinian Territory" => "Palestinian Territory",
    "Panama" => "Panama", "Papua New Guinea" => "Papua New Guinea",  "Paraguay" => "Paraguay",
    "Peru" => "Peru", "Philippines" => "Philippines",  "Pitcairn" => "Pitcairn",
    "Poland" => "Poland", "Portugal" => "Portugal", "Puerto Rico" => "Puerto Rico", "Qatar" => "Qatar",
    "Reunion" => "Reunion",  "Romania" => "Romania",  "Russian Federation" => "Russian Federation",
    "Rwanda" => "Rwanda",  "Saint Kitts and Nevis" => "Saint Kitts and Nevis",  "Saint Lucia" => "Saint Lucia",
    "Samoa" => "Samoa", "San Marino" => "San Marino", "Sao Tome and Principe" => "Sao Tome and Principe",
    "Saudi Arabia" => "Saudi Arabia", "Senegal" => "Senegal",  "Seychelles" => "Seychelles",
    "Sierra Leone" => "Sierra Leone",  "Singapore" => "Singapore", "Slovakia" => "Slovakia",
    "Slovenia" => "Slovenia", "Solomon Islands" => "Solomon Islands",  "Somalia" => "Somalia",
    "South Africa" => "South Africa", "Spain" => "Spain", "Sri Lanka" => "Sri Lanka",
    "St. Helena" => "St. Helena", "Sudan" => "Sudan", "Suriname" => "Suriname", "Swaziland" => "Swaziland", "Sweden" => "Sweden",
    "Switzerland" => "Switzerland", "Syria" => "Syria",  "Taiwan" => "Taiwan", "Tajikistan" => "Tajikistan",
    "Tanzania" => "Tanzania", "Thailand" => "Thailand",  "Togo" => "Togo", "Tokelau" => "Tokelau",
    "Tonga" => "Tonga",  "Trinidad and Tobago" => "Trinidad and Tobago",  "Tunisia" => "Tunisia",
    "Turkey" => "Turkey", "Turkmenistan" => "Turkmenistan", "Turks and Caicos islands" => "Turks and Caicos islands",
    "Tuvalu" => "Tuvalu", "Uganda" => "Uganda", "Ukraine" => "Ukraine", "United Arab Emirates" => "United Arab Emirates",
    "United Kingdom" => "United Kingdom","Uruguay" => "Uruguay", "Uzbekistan" => "Uzbekistan",
    "Vanuatu" => "Vanuatu", "Vatican City State" => "Vatican City State",  "Venezuela" => "Venezuela",
    "Viet Nam" => "Viet Nam",   "Virgin Islands (British)" => "Virgin Islands (British)",
    "Virgin Islands (U.S.)" => "Virgin Islands (U.S.)", "Wallis and Futuna Islands" => "Wallis and Futuna Islands",
    "Western Sahara" => "Western Sahara", "Yemen" => "Yemen","Yugoslavia" => "Yugoslavia", 
    "Zambia" => "Zambia",  "Zimbabwe" => "Zimbabwe");
?>